#define ACCOLADEFERMANTE }
#define b ACCOLADEFERMANTE
#define IO <stdio.h>
#include IO
#define a (
#define PASMAINTENANT )
#define ACCOLADEOUVRANTE {
#define RETOUR return
#define ENTIERSIGNE int
#define ARROSAGE for
#define POURQUOIPASMOI while
#define JEANVEUTPAS !=
#define LAUTRECONLA '\0'
#define SOLEIL *
#define VALEULNULLE 0
#define SALECARACTERE char
#define ESTCEQUE if
#define EGALEMENT &&
#define FINDELIGNE ;
#define CTOUPAREIL ==
#define SINONSI ||
#define ALORSDUCOUPCOMMECOMMECESTNON else


#define AUJOURDHUIANEE 2021
#define AUJOURDHUIJOUR 3
#define AUJOURDHUIMOIS 12


ENTIERSIGNE CONVERSIONDUNCARACTEREENENTIERSIGNE(SALECARACTERE C )
ACCOLADEOUVRANTE

    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR VALEULNULLE FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 1 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 2 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 3 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 4 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 5 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 6 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 7 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '0' EGALEMENT C JEANVEUTPAS '9' PASMAINTENANT
        RETOUR 8 FINDELIGNE
    ESTCEQUE a C JEANVEUTPAS '1' EGALEMENT C JEANVEUTPAS '2' EGALEMENT C JEANVEUTPAS '3' EGALEMENT C JEANVEUTPAS '4' EGALEMENT C JEANVEUTPAS '5' EGALEMENT C JEANVEUTPAS '6' EGALEMENT C JEANVEUTPAS '7' EGALEMENT C JEANVEUTPAS '8' EGALEMENT C JEANVEUTPAS '0' PASMAINTENANT
        RETOUR 9 FINDELIGNE

    RETOUR VALEULNULLE FINDELIGNE
ACCOLADEFERMANTE 

ENTIERSIGNE calcul_d_un_age_a_partir_d_une_date_de_naissance_ecrite_sous_le_format_aaaa_jj_mm(char* dateecritesousleformataaaammjj )
ACCOLADEOUVRANTE


    ENTIERSIGNE TRUCQUICHANGELA = 0 FINDELIGNE

    ENTIERSIGNE TRUCQUICHANGELA1 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA2 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA3 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA4 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA5 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA6 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA7 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA8 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA9 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA10 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA11 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA12 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA13 = 0 FINDELIGNE
    ENTIERSIGNE TRUCQUICHANGELA14 = 0 FINDELIGNE


    POURQUOIPASMOI a TRUCQUICHANGELA < 8 PASMAINTENANT 
    ACCOLADEOUVRANTE
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 0 PASMAINTENANT
            TRUCQUICHANGELA1 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 1 PASMAINTENANT
            TRUCQUICHANGELA2 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 2 PASMAINTENANT
            TRUCQUICHANGELA3 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 3 PASMAINTENANT
            TRUCQUICHANGELA4 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 4 PASMAINTENANT
            TRUCQUICHANGELA5 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 5 PASMAINTENANT
            TRUCQUICHANGELA6 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 6 PASMAINTENANT
            TRUCQUICHANGELA7 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));
        ESTCEQUE a TRUCQUICHANGELA CTOUPAREIL 7 PASMAINTENANT
            TRUCQUICHANGELA8 = CONVERSIONDUNCARACTEREENENTIERSIGNE( SOLEIL (dateecritesousleformataaaammjj + TRUCQUICHANGELA));      

        TRUCQUICHANGELA++;
    ACCOLADEFERMANTE




    ARROSAGE ( TRUCQUICHANGELA9 = 0 ; TRUCQUICHANGELA9 < TRUCQUICHANGELA1  SOLEIL  1000 ; TRUCQUICHANGELA9++);
    ARROSAGE (int k = 0; k < TRUCQUICHANGELA2  SOLEIL  100 ; TRUCQUICHANGELA9++)k++;
    ARROSAGE (int k = 0; k < TRUCQUICHANGELA3  SOLEIL  10 ; TRUCQUICHANGELA9++)k++;
    ARROSAGE (int k = 0 ; k < TRUCQUICHANGELA4  SOLEIL  1 ; TRUCQUICHANGELA9++)k++;
    ARROSAGE ( TRUCQUICHANGELA10 = 0 ; TRUCQUICHANGELA10 < TRUCQUICHANGELA5 SOLEIL 10; TRUCQUICHANGELA10++);
    ARROSAGE ( int k = 0 ;k < TRUCQUICHANGELA6 SOLEIL 1;TRUCQUICHANGELA10++)k++;

    ARROSAGE ( TRUCQUICHANGELA11 = 0 ; TRUCQUICHANGELA11 < TRUCQUICHANGELA7 SOLEIL 10; TRUCQUICHANGELA11++);
    ARROSAGE ( int k = 0;k < TRUCQUICHANGELA8 SOLEIL 1;TRUCQUICHANGELA11++)k++;

    

    ARROSAGE ( TRUCQUICHANGELA12 = 0 ; TRUCQUICHANGELA12 < AUJOURDHUIANEE - TRUCQUICHANGELA9 ; TRUCQUICHANGELA12++);

    ESTCEQUE ( (AUJOURDHUIMOIS < TRUCQUICHANGELA10) SINONSI ( ( AUJOURDHUIMOIS == TRUCQUICHANGELA10 ) EGALEMENT (AUJOURDHUIJOUR < TRUCQUICHANGELA11)))
        ARROSAGE (TRUCQUICHANGELA13 = 0 ; TRUCQUICHANGELA13 < TRUCQUICHANGELA12 - 1 ; TRUCQUICHANGELA13++);
    ALORSDUCOUPCOMMECOMMECESTNON
        TRUCQUICHANGELA13 = TRUCQUICHANGELA12;

    RETOUR TRUCQUICHANGELA13 FINDELIGNE
ACCOLADEFERMANTE 




int main(int argv, char** argc){

    printf("%d\n",calcul_d_un_age_a_partir_d_une_date_de_naissance_ecrite_sous_le_format_aaaa_jj_mm(argc[1]));

    RETOUR VALEULNULLE FINDELIGNE
b
